### ISSUE TITLE
Generate protostar based project.

### ISSUE THREAD

**Issue by abdelhamidbakhta** [onlydustxyz/generator-starknet#2]
# Description

Currently the generator only supports the generation of [nile](https://github.com/OpenZeppelin/nile) based projects. 
As a user, I want to generate a [protostar](https://github.com/software-mansion/protostar) based project.

# Acceptance criteria

- setup of the generated project should work following generated readme instructions
- generated projects can be compiled directly after generation
- generated projects can be tested (unit tests) directly after generation

**Comment by gaetbout** [comment]
Currently working on this. 
Hope to have something to merge on the 19th of May

**Comment by abdelhamidbakhta** [comment]
> Currently working on this. Hope to have something to merge on the 19th of May

Thanks

**Comment by gaetbout** [comment]
Still ongoing but encountering some configuration issues

**Comment by gaetbout** [comment]
Looks like their is an issue with some functionality of the Protostar lib.
Until it is fixed I'll put my work on hold.
