### ISSUE TITLE
Generate deployment scripts for Hardhat

### ISSUE THREAD

**Issue by abdelhamidbakhta** [onlydustxyz/generator-starknet#23]
## Description

As a developer, I would like to have deploy scripts generated for my project.

The deployment is an important part of the development lifecycle, hence it would improve the dev UX if the generator could prepare deployment scripts.

## Acceptance criteria

- A new confirm choice is proposed to the user to choose whether or not to generate the deployment scripts
- Deployment scripts are generated and working with Hardhat

**Comment by Bernardstanislas** [comment]
Closed by #37
