### ISSUE TITLE
Generate hardhat based project.

### ISSUE THREAD

**Issue by abdelhamidbakhta** [onlydustxyz/generator-starknet#3]
# Description

Currently the generator only supports the generation of [nile](https://github.com/OpenZeppelin/nile) based projects. 
As a user, I want to generate a [hardhat](https://github.com/Shard-Labs/starknet-hardhat-plugin) based project.

# Acceptance criteria

- setup of the generated project should work following generated readme instructions
- generated projects can be compiled directly after generation
- generated projects can be tested (unit tests) directly after generation

**Comment by gaetbout** [comment]
Hi,
I think this issue can be closed with the merge of fb1fda4194c33d639681f1348982b137e7109d55
Or does it still miss something?
K.R.,
G

**Comment by abdelhamidbakhta** [comment]
> Hi, I think this issue can be closed with the merge of [fb1fda4](https://github.com/onlydustxyz/generator-starknet/commit/fb1fda4194c33d639681f1348982b137e7109d55) Or does it still miss something? K.R., G

Indeed. thanks
